# Setup
title:          tbc
tagline:        A site for microbial bioinformatics, blogs and tutorials
baseurl:        ""
paginate:       1
future:         true
author:         Will Rowe

# Gems
gems:
        - jekyll-paginate

# Markdown
markdown:       kramdown
