# Setup
title: Will Rowe
email: will.rowe@liverpool.ac.uk

description: general blog site
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://will-rowe.github.io" # the base hostname & protocol for your site

# Social links
twitter_username:     will__rowe
github_username:      will-rowe
linkedin_username:    will-rowe-13219b136
alternate_site:       http://www.hintonlab.com
google_plus_username:
facebook_username:
dribbble_username:

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Slides
collections:
  - slides
