# Setup
title:        Hinton Lab Wiki
tagline:      A site for microbial bioinformatics, blogs and tutorials
baseurl:      ""
paginate:     1
future:       true

# About/contact
author:
  name:       Will Rowe
  url:        https://wpmr2.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
